### ISSUE TITLE
The panic hiding issue has returned in v3.4.0

### ISSUE THREAD

**Issue by nordicdyno** [gojuno/minimock#120]
panic hiding issue fixed here https://github.com/gojuno/minimock/issues/91 returned in  [v3.4.0](https://github.com/gojuno/minimock/releases/tag/v3.4.0)

I've checked [v3.3.14](https://github.com/gojuno/minimock/releases/tag/v3.3.14) behaviour is ok, but after v3.4.0 I've got pre fix behaviour (i.e. buggy one), demo is here: https://github.com/nordicdyno/minimock-panic

**Comment by zcolleen** [comment]
@nordicdyno hey! Sorry but i dont see the issue, i've cloned your repo, executed your test with v3.4.0 and panic is there. You just remove recover and you see that panic is there.

**Comment by nordicdyno** [comment]
Oh, I see. My fault. Cool! Thank you!
