### ISSUE TITLE
Suggestion: fail test explicitly when minimock version used for codegen is different from runtime version

### ISSUE THREAD

**Issue by vlanse** [gojuno/minimock#121]
In some cases there could be weird behavior, e.g. AnyContext comparison not working in case of different version, when code is generated with different version than the one used for actual test execution.

I suggest to fail test explicitly when version difference is detected.

P.S. "fatal" version difference could be calculated based on semver, but IMO just basic comparison is enough

**Comment by vlanse** [comment]
AnyContext case is just an example, IMO no need to fix anything related to it.

> Do you have a separate packages with mocks and tests

of course, no. Mocks were just generated at some moment in the past with older version of minimock. And library version itself was updated eventually in go.mod. Thus, new tests are run with that version using "old" mocks

**Comment by hexdigest** [comment]
This shouldn't be the case then. 
You just have to re-generate your mocks because they're probably just unaware of AnyContext which was introduced just recently.

**Comment by vlanse** [comment]
But to regen mocks one needs to find the reason. Thats why i created this issue

**Comment by hexdigest** [comment]
This is the reason :point_up:

**Comment by vlanse** [comment]
Btw, AnyContext was only one example of possible problems.

**Comment by hexdigest** [comment]
The fact that you have an old **generated** code and try to use somewhat new functionality isn't a problem of the code generation tool (any code generation tool, incl minimock). You can always re-generate the code if you'd like to use AnyContext or any other new functionality that isn't supported by the old mock template. There's no general solution to this except mocks regen.

We probably could inject some callback from the mock controller that will be executed when evaluating arguments for example. But this won't solve the problem with old mocks anyways, also sometimes people don't use minimock.Controller.

**Comment by vlanse** [comment]
You are right, w/o using controller, it makes no sense. I just missed this.
