### ISSUE TITLE
FeatureRequest: named input arguments for functions

### ISSUE THREAD

**Issue by beono** [gojuno/minimock#22]
For example, I have an interface:

```go
type FileUploader interface {
	Save(ctx context.Context, Data []byte, Filename string) (*FileInfo, error)
}
```

Than, I have to work with arguments `p, p1, p2`.
```go
mockFileStorage.SaveMock.Set(func(p context.Context, p1 []byte, p2 string) (r *FileInfo, r1 error) {
```

Instead, I would like to see names of variables according to interface declaration (`ctx, Data, Filename`).
Also I don't think we need to pre allocate return values (`r` and `r1`)

```go
mockFileStorage.SaveMock.Set(func(ctx context.Context, Data []byte, Filename string) (*FileInfo, error) {
```

**Comment by hexdigest** [comment]
Hi @beono 

Sorry for the delayed response. This should be fixed with minimock v2.0.0 please check it out and feel free to reopen the issue if the problem still exists.
