### ISSUE TITLE
Implement a way to skip checking expectations for a mock object

### ISSUE THREAD

**Issue by Kangaroux** [gojuno/minimock#38]
Based on #35.

It would be great if a mock could be skipped when the mock controller checks to see if expectations were met. This has several use cases:

- Argument values are not known at runtime (e.g. random)
- Argument value is complex (e.g. struct with private fields)
- Mocking an interface to either make a no-op implementation or to capture call args (satisfies both the above points and reduces boilerplate)

Some possible naming schemes:

```go
FooMock.ExpectAnything().Return("val")
FooMock.SkipExpectations()
FooMock.CaptureOnly()
```

`ExpectAnything` implies that the mock will be called at least once. `SkipExpectations` is the least vague IMO. `CaptureOnly` makes it sound like a `Return()` wouldn't work which probably isn't the desired functionality.

**Comment by hexdigest** [comment]
@Kangaroux 

I just remembered that recently we changed the generated code that Return works without preceeding Expect.

So
```go
FooMock.ExpectAnything().Return("something")
```

Is already supported by the:
```go
FooMock.Return("val")
```

Notation

So if there are no calls to Expect/When/Then there're no expectations to be met.

**Comment by jesseroux** [comment]
@hexdigest Ok great. Is that documented somewhere? I can't test it right now but I recall seeing an error like `unexpected call to mock`. I don't believe I set a `Return()` on that particular mock, though. So I assume it means that there needs to be at least a `Return()` on the mock?

**Comment by hexdigest** [comment]
@jesseroux yes there need to be at least a Return() call on the mock.

**Comment by jesseroux** [comment]
@hexdigest OK. I'll make a PR later to clarify that then

**Comment by hexdigest** [comment]
@jesseroux great! Can you please also mention Calls() method that you just added?

**Comment by Kangaroux** [comment]
@hexdigest Just to clarify about not needing an `ExpectAnything` method, because the current docs say that isn't how it works: https://godoc.org/github.com/gojuno/minimock#hdr-Keep_your_tests_clean

If the docs weren't updated when the `Return()` change was made I can just remove that section.

**Comment by hexdigest** [comment]
@Kangaroux can you please clarify what confuses you in the docs? What I wanted to say in this section is that Expect/Return/When/Then initialize a mock for some method and if you initialized a mock then MockController.Finish() ensures that this particular method has been called during the test.

The fact that you created an instance of the mock, i.e. `readCloserMock := NewReadCloserMock(mc)` isn't checked by Finish() but the compiler won't compile the test if there's no usage of `readCloserMock`.

**Comment by hexdigest** [comment]
@Kangaroux please follow this thread: 
https://github.com/gojuno/minimock/issues/30

Maybe new `Inspect` helper is enough for you?
