### ISSUE TITLE
Use more unique variable name for mock

### ISSUE THREAD

**Issue by jonathanbp** [gojuno/minimock#39]
I have a generated mock that doesn't compile because it has a method where one of the arguments has the name `m`. This conflicts with the `m` name given to the mock itself in the `Expect` method:

```go
func (m *mContextManager_ContextParticipantStreamServerMockRecvMsg) Expect(m interface{}) *mContextManager_ContextParticipantStreamServerMockRecvMsg {
...
```

This could be fixed by having a more unique name for the mock (in `template.go`?), I think.

**Comment by hexdigest** [comment]
Hi @jonathanbp !

Thanks for raising the issue, please check that v2.1.7 works for you.

**Comment by jonathanbp** [comment]
It works - thanks for the quick response!
