### ISSUE TITLE
add v1.9.2 tag

### ISSUE THREAD

**Issue by rogpeppe** [gojuno/minimock#43]
As v2 introduces API-breaking changes, we have a lot of code that can't yet move off v1. Please could you add a `v1.9.2` tag (the same as the current `1.9.2` tag) so that v1 minimock plays better with Go modules? Thanks!

**Comment by hexdigest** [comment]
Hi @rogpeppe !

Can you please clarify how adding this tag would help?

**Comment by rogpeppe** [comment]
The go tool does not recognize `1.9.2` as a valid version tag. I recently saw people suggesting that it be installed using the pseudo-version (v0.0.0-20190130082935-96af809257c4). While it is actually possible to use the real version (github.com/gojuno/minimock/cmd/minimock@1.9.2), that just resolves to the pseudo-version under the hood.

It would be nice if the actual version was tagged, avoiding the need to use pseudo-versions. I don't think there are any disadvantages in doing so.

**Comment by hexdigest** [comment]
@rogpeppe got it, thank you for posting this issue!
I just added v1.9.2 tag. Can you please check if it works for you?

**Comment by rogpeppe** [comment]
That works great now, thanks!
