### ISSUE TITLE
Consider purging vendor directory

### ISSUE THREAD

**Issue by shoenig** [gojuno/minimock#44]
Now that m`minimock` is using Go modules, it seems redundant to have the `vendor` directory. Modules are publicly served via `proxy.golang.org`, and paranoid orgs will typically run an additional internal proxy. The `vendor` directory is also ignored by default.
https://github.com/golang/go/wiki/Modules#how-do-i-use-vendoring-with-modules-is-vendoring-going-away

**Comment by hexdigest** [comment]
Hi @shoenig 
Done, thanks for the input!
