### ISSUE TITLE
Proposal: add .Panic() alongside .Return(...) for interrupting a test

### ISSUE THREAD

**Issue by unkeep** [gojuno/minimock#51]
It would be useful for testing expectations which do not return an error or the error does not interrupt a flow.

example code:
```go
func foo(dep Dependency) {
    dep.doSmth1(...)
    dep.doSmth2(...)
}
```

example test:
```go
It("should doSmth1", func(){
    depMock.Expect(...).Panic()
    Ω(func(){foo(depMock)}).Should(Panic())
})
```

Of course the same could be done by adding panic() to the end of Inspect func, but the proposed way is more natural and shorter

**Comment by hexdigest** [comment]
Hey, you can achieve the same using `Set`:

```go
It("should doSmth1", func(){
    depMock.Set(func(...) {
       panic("is good for you")
    })
    Ω(func(){foo(depMock)}).Should(Panic())
})
```

I don't think it deserves a special helper.
