### ISSUE TITLE
Set type name for generated mock

### ISSUE THREAD

**Issue by rekby** [gojuno/minimock#56]
For example I want generate mock for interface ```test/test.Interface```. Now generated class will have name ```InterfaceMock```.
I want some similar to ```minimock -i test/test.Interface -name TestInterfaceMock``` and have generated name ```TestInterfaceMock```.

And it nesessary if I want to mock two interfaces ```test/test.Interface``` and ```test/test2.Interface``` to one dest package.

Now I use workaround and create stub interface in dest package:
```
import "test/test"

type testInterface interface {
  test.Interface
}
```

**Comment by damianopetrungaro** [comment]
@rekby @hexdigest this can be marked as done

**Comment by hexdigest** [comment]
@rekby please take a look at -n flag in [v3.0.9](https://github.com/gojuno/minimock/releases/tag/v3.0.9)
