### ISSUE TITLE
generating a file that doesn't compile

### ISSUE THREAD

**Issue by ovesh** [gojuno/minimock#58]
Minimock is generating a file that doesn't compile:
`go run github.com/gojuno/minimock/v3/cmd/minimock -g -i k8s.io/client-go/kubernetes/typed/core/v1.ServiceInterface`

The generated file is referencing a package (`restclient`) that isn't being imported.

minimock version: v3.0.9
k8s.io/client-go version: v0.21.3

**Comment by ovesh** [comment]
`ServiceInterface` is embedding another interface `ServiceExpansion` which is bringing in an extra function `ProxyGet`. The return type for that function isn't being imported.

**Comment by ovesh** [comment]
This is actually a bug in github.com/hexdigest/gowrap, at least in v1.1.8. Specifically, the list of import added [here](https://github.com/hexdigest/gowrap/blob/v1.1.8/generator/generator.go#L138) doesn't contain the extra import needed for the return value.

**Comment by hexdigest** [comment]
Hey, I'm unable to reproduce this because k8s.io/client-go/kubernetes/typed/core/v1.ServiceInterface is gone forever I guess. 

Feel free to re-open if you find another way to repro this.
