### ISSUE TITLE
Use `t.Cleanup()` in constructor

### ISSUE THREAD

**Issue by maratori** [gojuno/minimock#62]
Now I have to remember to add `defer` or `t.Cleanup` in each test manually.
```go
func TestSomething(t *testing.T) {
  formatterMock := NewFormatterMock(t)
  defer formatterMock.Finish()
  ...
}
```
or
```go
func TestSomething(t *testing.T) {
  formatterMock := NewFormatterMock(t)
  t.Cleanup(formatterMock.Finish)
  ...
}
```
It would be great to do it automatically in mock constructor like gomock does. Of course only if it's go 1.14 or newer.

**Comment by hexdigest** [comment]
Hey @maratori 

This is a really good proposal. It's available in [v3.3.0](https://github.com/gojuno/minimock/releases/tag/v3.3.0).
Please let me know if you find any issues with it.

Thank you!
