### ISSUE TITLE
Allow expected counter for concrete controller's method

### ISSUE THREAD

**Issue by CyganFx** [gojuno/minimock#66]
Hi, I think there is an often case when we need to set expected times that concrete controller method will be executed during the test. Currently, `<method>AfterCounter` allows only to get the current value of calls to the mocked method, which is useless in table tests and lead to potential logical errors to pass the test.

There is a convenient method `Times(N)` in gomock. Could you add a similar one?

**Comment by zcolleen** [comment]
@CyganFx hi, thanks for issue. In this case we could use `<method>AfterCounter` but i agree that it is not very convenient way when you write table test and want to chain expectations. Feature could be added in pr above
