### ISSUE TITLE
Mock for generic interface failed

### ISSUE THREAD

**Issue by musinit** [gojuno/minimock#73]
The error: **failed to find any interfaces matching Interface[T in {package_name}**

I have an ICache[T any] interface and I am trying to mock it with flag -i ICache[T any]

**Comment by hexdigest** [comment]
Hi @musinit 

It should work but you have to slightly change you command line, examples can be found here:
```bash
$ ag genericSimpleUnion
Makefile
14:	go run ./cmd/minimock/minimock.go -i ./tests.genericSimpleUnion -o ./tests/generic_simple_union.go

tests/types.go
51:	genericSimpleUnion[T simpleUnion] interface {
```

in your case it should be just `-i ICache`
