### ISSUE TITLE
Prebuilt binaries for darwin/arm64 and windows/arm64 are missing from v3.2.0

### ISSUE THREAD

**Issue by suzuki-shunsuke** [gojuno/minimock#79]
v3.1.3 has prebuilt binaries for darwin/arm64 and windows/arm64.

https://github.com/gojuno/minimock/releases/tag/v3.1.3

- [minimock_3.1.3_darwin_arm64.tar.gz](https://github.com/gojuno/minimock/releases/download/v3.1.3/minimock_3.1.3_darwin_arm64.tar.gz)
- [minimock_3.1.3_windows_arm64.tar.gz](https://github.com/gojuno/minimock/releases/download/v3.1.3/minimock_3.1.3_windows_arm64.tar.gz)

<img width="630" alt="image" src="https://github.com/gojuno/minimock/assets/13323303/1147924e-24a3-44b0-889e-a1afcc3ba75c">

But v3.2.0 or newer don't have them.

<img width="406" alt="image" src="https://github.com/gojuno/minimock/assets/13323303/0515665d-ee4d-496e-896a-9fc13a7f8e14">

**Comment by suzuki-shunsuke** [comment]
I found https://github.com/gojuno/minimock/blob/master/.goreleaser.yml , but I don't know how prebuilt binaries are released.
It seems CI services such as GitHub Actions and CircleCI aren't used.

https://github.com/gojuno/minimock/actions

**Comment by hexdigest** [comment]
Hi @suzuki-shunsuke 

I release this manually from my local machine using goreleaser.
I updated goreleaser version and released darwin and win executables for arm64:

https://github.com/gojuno/minimock/releases/tag/v3.3.2

**Comment by suzuki-shunsuke** [comment]
Thank you!
I think it's great if we can release minimock via CI such as GitHub Actions.
CI would be also useful to test minimock.
I'll create issues.
