### ISSUE TITLE
Run tests on CI

### ISSUE THREAD

**Issue by suzuki-shunsuke** [gojuno/minimock#80]
It seems no test and lint aren't run on CI.
How about running tests and lint on CI with GitHub Actions?

- go vet
- go test

Then we can find issues quickly before merging pull requests.

If this proposal is acceptable, I'm interested in working on this.

**Comment by hexdigest** [comment]
we should do it, but I'd rather use `make lint` for lint/vet
and `make test` for tests

**Comment by suzuki-shunsuke** [comment]
- https://github.com/gojuno/minimock/pull/82
